### ISSUE TITLE
Odd use of foreach/2

### ISSUE THREAD

**Issue by pmoura** [metagol/metagol#16]
This is an odd use of the (non-standard) `foreach/2` predicate:

https://github.com/metagol/metagol/blob/39033ba25c3989a9230da9301128e50bc349cec3/metagol.pl#L311

Moreover, `memberchk/2` will succeed at most once. I would expect instead:

```prolog
forall(member(Clause,Prog2),assert(user:Clause)),
```

Typo?

**Comment by andrewcropper** [comment]
That is indeed a bug. I will fix and refactor that part of the code. Thank you for spotting it.

**Comment by andrewcropper** [comment]
Fixed with commit 88aed2959d74b601b8e4f471745e9ed402de98ac
