### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by teriterance** [metagol/metagol#22]
My configuration:
OS : Window 10
SWI-Prolog Version 8.3.20

I am getting an error with all filles of the repository

Warning: [Thread pce] The predicates below are not defined. If these are define
Warning: [Thread pce] at runtime using assert/1, use :- dynamic Name/Arity.
Warning: [Thread pce] 
Warning: [Thread pce] func_test/3, which is referenced by
Warning: [Thread pce]   c:/users/user/desktop/metagol-master/metagol.pl:111:17: 1-st clause of metagol:check_functional/3

And 

ERROR: c:/users/user/desktop/metagol-master/examples/strings1.pl:27:
ERROR:    retractall/1: No permission to modify static procedure `body_pred/1'
ERROR:    Defined at c:/users/user/desktop/metagol-master/examples/strings1.pl:4
Warning: c:/users/user/desktop/metagol-master/examples/strings1.pl:27:
Warning:    Goal (directive) failed: user:time(a)

**Comment by andrewcropper** [comment]
Hi,

I am sorry but Windows is unsupported by Metagol. 

Kind regards,

Andrew

**Comment by pmoura** [comment]
Note that the Logtalk [port](https://github.com/LogtalkDotOrg/logtalk3/tree/master/ports/metagol) of Metagol runs fine on Windows and currently supports ECLiPSe, SICStus Prolog, SWI-Prolog, and YAP.
